# image will be published to ghcr.io/<user>/<name>
name: sway
# description will be included in the image's metadata
description: ublue images for wayland compositors

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - from-file: common-packages.yml

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
